As/download panel triggered on content disposition attachment
mozilla/fx-desktop-qa-automation pull request #165
Opened 2024-08-07 15:09 UTC by soncuteanca

# Description

Ensure that the "Always ask" option in Firefox Applications settings triggers the download panel for PDFs with Content-Disposition: attachment.

## Bugzilla bug ID

**Testrail: https://bugzilla.mozilla.org/show_bug.cgi?id=1910705**
**Link: https://mozilla.testrail.io/index.php?/cases/view/936502**

## Type of change

Please delete options that are not relevant.

- [x ] New Test

# How does this resolve / make progress on that bug?

Please describe the progress or significance with respect to the bug listed above.
Completed

# Screenshots / Explanations

Please upload any relevant media or add a relevant description with respect to the bug listed above.

# Comments / Concerns

Please add a short blurb about any comments or concerns that this change might cause.

2024-08-08 15:58 UTC, vsangereanMOZ reviewed
lgtm

2024-08-08 16:45 UTC, ben-c-at-moz requested changes
Looks like we're going to need a path for Linux using pynput--this is a common problem with using auto-GUI libraries in that Linux key paths often differ from Mac and Win...I'll try to find a way around using pynput when I have a chance

2024-08-08 20:25 UTC, ben-c-at-moz approved these changes
Changed a selector and its name, but ran into the same problem you were having with the menu items. Instead of pynput, I'm sending keys to elements, and that seems to be working better

2024-08-09 15:14 UTC, ben-c-at-moz approved these changes

2024-08-12 06:00 UTC, merged