improve fluent interface on PoM, tests
mozilla/fx-desktop-qa-automation pull request #2
Opened 2024-04-03 22:19 UTC by ben-c-at-moz

* Improve the POMs to be more amenable to the Fluent Interface model
* Refactor tests to use chained methods
* Fix return type typos in Browser Object Model

2024-04-08 14:03 UTC, b4handjr commented on modules/browser_object_navigation.py
> +        self.resume_content_context()
Looks like a good spot for a context manager

2024-04-08 14:59 UTC, b4handjr commented on modules/browser_object_navigation.py
> +        return self
Should this go in more of a "base" class? This seems more generic and could be useful elsewhere

2024-04-08 14:59 UTC, b4handjr commented on tests/address_bar_and_search/test_search_modes_for_sites.py
> +    )
Why is this in parenthesis?

2024-04-08 15:01 UTC, b4handjr commented on modules/page_object_about_logins.py
> +        self.add_login_button().click()
`add_login_button` could be a property so the call would look like `self.add_login_button.click()`. Just a thought.

2024-04-09 13:59 UTC, ben-c-at-moz commented on modules/browser_object_navigation.py
> +        self.resume_content_context()
good call!

2024-04-09 14:00 UTC, ben-c-at-moz commented on modules/browser_object_navigation.py
> +        return self
Yeah, trying to think about how exactly that would work, but you're absolutely right.

2024-04-09 14:03 UTC, ben-c-at-moz commented on tests/address_bar_and_search/test_search_modes_for_sites.py
> +    )
So this is kinda the meat of this diff, it's thinking about how we can use Fluent Interface patterns in testing in Python without making gross looking lines or breaking PEP8. So far, it's parens. The other option is to just reiterate the object:

```Python
nav.set_search_mode_via_awesome_bar(site)
nav.type_in_awesome_bar("soccer" + Keys.RETURN)
...
```

Which do you prefer?

2024-04-09 14:04 UTC, ben-c-at-moz commented on modules/page_object_about_logins.py
> +        self.add_login_button().click()
also a good call

2024-04-09 14:30 UTC, ben-c-at-moz commented on modules/browser_object_navigation.py
> +        return self
I think I got it

2024-04-09 15:14 UTC, jrbenny35 commented on tests/address_bar_and_search/test_search_modes_for_sites.py
> +    )
Ah I gotcha. I am more used to the latter but wouldn't be opposed to yours looking different. It's more so your choice!

2024-04-09 15:19 UTC, jrbenny35 requested changes
Lots of nice changes, just had some follow up thoughts

2024-04-09 15:19 UTC, jrbenny35 commented on modules/page_base.py
> +        return self
Personally love this!

2024-04-09 15:19 UTC, b4handjr commented on modules/browser_object_navigation.py
> +            if mode is not None:
This could be `if mode`

2024-04-09 15:19 UTC, jrbenny35 commented on modules/browser_object_navigation.py
> +        self.awesome_bar.clear()
This looks a little weird, you're not returning the awesome bar from `get_awesome_bar` but you can clear it?

2024-04-10 01:41 UTC, jrbenny35 approved these changes
/giphy "just gonna send it", Nice work!

2024-04-10 19:17 UTC, merged