Sl/form autofill 4 fields
mozilla/fx-desktop-qa-automation pull request #23
Opened 2024-05-17 18:52 UTC by sarinali

# Description

Completes the Autofill 4 Fields and verify test. 

## Bugzilla bug ID

**ID:** https://bugzilla.mozilla.org/show_bug.cgi?id=1895892
**Link:** 1895892

## Type of change

Please delete options that are not relevant.

- [x] New Test

# How does this resolve / make progress on that bug?

Completed.

# Screenshots / Explanations

N/A

# Comments / Concerns

N/A

2024-05-17 23:03 UTC, ben-c-at-moz requested changes

2024-05-17 23:03 UTC, ben-c-at-moz commented on tests/form_autofill/test_autofill_credit_card.py
> +    ccf = CreditCardFill(driver).open()
I would prefer longer names for these variables. If this file grows it may become difficult to remember what each of these acronyms refers to.

2024-05-28 15:08 UTC, ben-c-at-moz commented on modules/page_object_autofill_credit_card.py
>      def fake_and_fill(self, util: Utilities, autofill_popup_obj: AutofillPopup):
I would love for this function to return `self` so we can maintain our Fluent Interface design

2024-05-28 15:08 UTC, ben-c-at-moz commented on modules/page_object_autofill_credit_card.py
>      def fake_and_fill(self, util: Utilities, autofill_popup_obj: AutofillPopup):
(Also the error on Alpenglow mentioned above)

2024-05-29 13:36 UTC, sarinali commented on modules/page_object_autofill_credit_card.py
>      def fake_and_fill(self, util: Utilities, autofill_popup_obj: AutofillPopup):
I'm going to resolve the alpenglow issue on the related themes PR

2024-05-29 19:16 UTC, ben-c-at-moz requested changes
Still getting `FAILED tests/form_autofill/test_autofill_credit_card.py::test_autofill_four_fields - AttributeError: 'list' object has no attribute 'get_attribute`

2024-05-29 19:16 UTC, ben-c-at-moz commented on modules/page_object_autofill_credit_card.py
> +    ):
Put a return type in the function signature (`Autofill`)

2024-05-29 19:16 UTC, ben-c-at-moz commented on modules/page_object_autofill_credit_card.py
> +        Veriies that after clicking the autofill panel the information is filled correctly.
Typo

2024-05-29 19:38 UTC, sarinali commented
> Still getting `FAILED tests/form_autofill/test_autofill_credit_card.py::test_autofill_four_fields - AttributeError: 'list' object has no attribute 'get_attribute`

I fixed it locally now. I'm wondering tho, why didn't this fail in CI?

2024-05-29 22:41 UTC, ben-c-at-moz commented
> > Still getting `FAILED tests/form_autofill/test_autofill_credit_card.py::test_autofill_four_fields - AttributeError: 'list' object has no attribute 'get_attribute`
> 
> I fixed it locally now. I'm wondering tho, why didn't this fail in CI?

Because it wasn't run! We need to make sure folks are running their pre-commit checks. Please checkout `main` and run `./devsetup.sh` as soon as is reasonable.

2024-05-29 22:45 UTC, ben-c-at-moz approved these changes
Good to go.

2024-05-29 22:45 UTC, merged