Sl/tell attribute autofill
mozilla/fx-desktop-qa-automation pull request #30
Opened 2024-05-23 19:40 UTC by sarinali

# Description

Completed the telephone autofill test

## Bugzilla bug ID

**ID:** 1895880 
**Link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1895880

## Type of change

Please delete options that are not relevant.

- [x] New Test

# How does this resolve / make progress on that bug?

Finishes it.

# Screenshots / Explanations

N/A

# Comments / Concerns

There is a bug where the telephone field autofills inconsistently, in the final version of this PR the `test.sh` and `.log` file will be removed, for now they are there for testing purposes to demonstrate its flakiness... Hopefully there is a fix for this, all other fields do not have this issue.

2024-05-27 13:48 UTC, sarinali commented
> The test fails on Beta build with: FAILED tests/form_autofill/test_enable_disable_autofill.py::test_telephone_attribute_autofill[CA] - AssertionError: assert '2681953596' == '268-195-3596' FAILED tests/form_autofill/test_enable_disable_autofill.py::test_telephone_attribute_autofill[US] - AssertionError: assert '6214508112' == '621-450-8112'
> 
> The test fails on Nightly build with: FAILED tests/form_autofill/test_enable_disable_autofill.py::test_telephone_attribute_autofill[CA] - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) FAILED tests/form_autofill/test_enable_disable_autofill.py::test_telephone_attribute_autofill[US] - selenium.common.exceptions.TimeoutException: Message:

For the first error, I fixed the normalization algorithm. My bad. 

For the second error, Nightly and Firefox just seem to have differences between the two, I wrote a TODO comment to remind later to fix, can that suffice for now?

2024-05-28 13:52 UTC, Tracy-Walker commented
Per Ben, we're targeting Beta, not Nightly. so that's fine. However, when I run your current test i get the following:
======================= short test summary info ===============================================
FAILED tests/form_autofill/test_telephone_autofill_attribute.py::test_telephone_attribute_autofill[CA] - TypeError: Utilities.generate_localized_phone_US_CA() takes 2 positional arguments but 3 were given
FAILED tests/form_autofill/test_telephone_autofill_attribute.py::test_telephone_attribute_autofill[US] - TypeError: Utilities.generate_localized_phone_US_CA() takes 2 positional arguments but 3 were given

2024-05-28 14:46 UTC, ben-c-at-moz requested changes
Getting the same test errors as Tracy. Fix those and I'll relook, thx

2024-05-29 17:50 UTC, ben-c-at-moz approved these changes
LGTM

2024-05-29 17:50 UTC, merged