Menu Copy and Paste
mozilla/fx-desktop-qa-automation pull request #71
Opened 2024-06-19 15:46 UTC by sarinali

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Bugzilla bug ID

**ID:** 1902755
**Link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1902755

## Type of change

Please delete options that are not relevant.

- [x] New Test
- [x] New POM

# How does this resolve / make progress on that bug?

Done.

# Screenshots / Explanations

N/A

# Comments / Concerns

N/A

2024-06-20 17:04 UTC, ben-c-at-moz requested changes
A few small things, which is great for a test of this size. Good job!

2024-06-20 17:04 UTC, ben-c-at-moz commented on modules/page_base.py
> +    def triple_click(self, name: str, labels=[]):
lol, I love that we have to roll this ourselves

2024-06-20 17:04 UTC, ben-c-at-moz commented on modules/util.py
> +    def generate_random_text(
Nice, I like this a lot. I might be using Literal when I refactor, seems cleaner than some other things I've done.

2024-06-20 17:04 UTC, ben-c-at-moz commented on tests/menus/test_copy_paste_actions.py
> +    assert password_field.get_attribute("value") != random_text
Is there a reason we're not asserting `== ''`? I'm fine if there is one, just wondering.

2024-06-20 17:04 UTC, ben-c-at-moz commented on tests/menus/test_copy_paste_actions.py
> +    # initialize obbjects
spelling

2024-06-20 17:04 UTC, ben-c-at-moz commented on tests/menus/test_copy_paste_actions.py
> +    text_area.send_keys(Keys.BACK_SPACE)
Should probably check that the text area is cleared.

2024-06-20 17:04 UTC, ben-c-at-moz commented on tests/menus/test_copy_paste_actions.py
> +    search_bar.send_keys(Keys.BACK_SPACE)
Should probably check that the search bar is cleared.

2024-06-20 17:48 UTC, sarinali commented on tests/menus/test_copy_paste_actions.py
> +    assert password_field.get_attribute("value") != random_text
you would have to ensure that the clipboard is clear before testing, this is OS specific which is more work and this has about the same effect

2024-06-21 18:04 UTC, ben-c-at-moz approved these changes
let's gooooooo

2024-06-21 18:33 UTC, merged