As/adaptive history autofill
mozilla/fx-desktop-qa-automation pull request #89
Opened 2024-07-03 16:14 UTC by soncuteanca

# Description

Test to verify that typing the first three characters of a previously visited URL in the address bar triggers the adaptive history autofill.

## Bugzilla bug ID

**ID: 1902773**
**Link: https://bugzilla.mozilla.org/show_bug.cgi?id=1902773**

## Type of change

Please delete options that are not relevant.

- [x ] New Test

# How does this resolve / make progress on that bug?
- Completed

Please describe the progress or significance with respect to the bug listed above.

# Screenshots / Explanations

Please upload any relevant media or add a relevant description with respect to the bug listed above.

# Comments / Concerns

Please add a short blurb about any comments or concerns that this change might cause.

2024-07-03 17:24 UTC, ben-c-at-moz requested changes
One small thing, the rest looks great!

2024-07-03 17:24 UTC, ben-c-at-moz commented on tests/address_bar_and_search/test_adaptive_history_autofill.py
> +    tabs.new_tab_by_button()
we need to switch to the new tab before we can confirm this worked:
```python
tabs.wait_for_num_tabs(2)
driver.switch_to.window(driver.window_handles[-1])
```

2024-07-08 12:29 UTC, emilghittasv requested changes

2024-07-08 12:29 UTC, emilghittasv commented on tests/address_bar_and_search/test_adaptive_history_autofill.py
> +    tabs.new_tab_by_button()
@soncuteanca  `tabs.wait_for_num_tabs(2)` is going to fail here because the window handles list will suffer modifications due to the context switch which is happening in `nav.type_in_awesome_bar` function. 
 
 We need to switch drivers context back to content after the EC check.

2024-07-08 12:29 UTC, emilghittasv commented on tests/address_bar_and_search/test_adaptive_history_autofill.py
> +
Add `tabs.set_content_context()` to switch context back to content.

2024-07-08 12:45 UTC, soncuteanca commented on tests/address_bar_and_search/test_adaptive_history_autofill.py
> +
Done

2024-07-08 12:48 UTC, soncuteanca commented on tests/address_bar_and_search/test_adaptive_history_autofill.py
> +    tabs.new_tab_by_button()
I've updated the test accordingly.

2024-07-08 22:15 UTC, ben-c-at-moz approved these changes
Looks good!

2024-07-09 07:26 UTC, emilghittasv approved these changes
approved!

2024-07-09 07:27 UTC, merged