Firefox Home New Tab
mozilla/fx-desktop-qa-automation pull request #99
Opened 2024-07-08 18:56 UTC by sarinali

# Description

Verifies that upon changing the default new tab, the correct content is shown.

## Bugzilla bug ID

**Testrail:** https://testrail.stage.mozaws.net/index.php?/cases/view/161472
**Link:** https://bugzilla.mozilla.org/show_bug.cgi?id=1905167

## Type of change

Please delete options that are not relevant.

- [x] New Test

# How does this resolve / make progress on that bug?

Completes.

# Screenshots / Explanations

N/A

# Comments / Concerns

Verifying about:home in this code means checking that the logo shows up. Note that on about:blank, the logo doesn't exist and those are the only two options so hence why I chose that as an indicator.

2024-07-09 16:01 UTC, ben-c-at-moz requested changes
Just one thing, but I think it's important

2024-07-09 16:01 UTC, ben-c-at-moz commented on tests/preferences/test_firefox_home_new_tabs.py
Please move this to tests/about_prefs

2024-07-09 16:10 UTC, sarinali commented on tests/preferences/test_firefox_home_new_tabs.py
This is part of the new suite, listed in the sheet. Should that be moved as well?

2024-07-09 16:26 UTC, ben-c-at-moz commented on tests/preferences/test_firefox_home_new_tabs.py
Wait, ok hold on...

2024-07-09 16:55 UTC, Tracy-Walker commented on tests/preferences/test_firefox_home_new_tabs.py
no, if anything, that about_prefs test should be moved into the preferences test suite.  But what is that test?  no TestRail reference.  Was that just a proof of concept test, Ben?

2024-07-09 18:52 UTC, sarinali commented on tests/preferences/test_firefox_home_new_tabs.py
all good, i moved it since theyre the same suite

2024-07-10 15:42 UTC, ben-c-at-moz approved these changes
LGTM!

2024-07-10 17:49 UTC, ben-c-at-moz approved these changes
LGTM

2024-07-10 18:30 UTC, merged